---
Name: external-newsletter
---
ExternalNewsletter:
  enabled:
    - 'mailchimp'
  drivers:
    mailchimp: 'Milkyway\SS\ExternalNewsletter\Providers\Mailchimp\Driver'

Controller:
  extensions:
    - 'Milkyway\SS\ExternalNewsletter\Extensions\Controller'