---
Name: external-newsletter
---
Injector:
  'Milkyway\SS\ExternalNewsletter\Contracts\Config':
    class: 'Milkyway\SS\ExternalNewsletter\Providers\Mailchimp\Config'
  'Milkyway\SS\ExternalNewsletter\Contracts\Campaign':
    class: 'Milkyway\SS\ExternalNewsletter\Providers\Mailchimp\Campaign'
  'Milkyway\SS\ExternalNewsletter\Contracts\Lists':
    class: 'Milkyway\SS\ExternalNewsletter\Providers\Mailchimp\Lists'
  'Milkyway\SS\ExternalNewsletter\Contracts\Subscriber':
    class: 'Milkyway\SS\ExternalNewsletter\Providers\Mailchimp\Subscriber'
---
Only:
  moduleexists: 'betterbuttons'
---
ExternalDataObject:
  extensions:
    - BetterButtonDataObject
---
Only:
  envvarset: 'campaignmonitor_api_key'
---
Injector:
  'Milkyway\SS\ExternalNewsletter\Contracts\Config':
    class: 'Milkyway\SS\ExternalNewsletter\Providers\CampaignMonitor\Config'
  'Milkyway\SS\ExternalNewsletter\Contracts\Campaign':
    class: 'Milkyway\SS\ExternalNewsletter\Providers\CampaignMonitor\Campaign'
  'Milkyway\SS\ExternalNewsletter\Contracts\Lists':
    class: 'Milkyway\SS\ExternalNewsletter\Providers\CampaignMonitor\Lists'
  'Milkyway\SS\ExternalNewsletter\Contracts\Subscriber':
    class: 'Milkyway\SS\ExternalNewsletter\Providers\CampaignMonitor\Subscriber'